# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  publish = "dist/"
  command  = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  # to = "/.netlify/functions/api.js/:splat"
  to = "/.netlify/functions/:splat"
  status = 200
